### ISSUE TITLE
Crash when mousing over shop tip at very start of run

### ISSUE THREAD

**Issue by casey-c** [casey-c/infomod2#4]
I suspect it's looking at data that doesn't exist until the game saves the first time. Need to investigate further [priority: highest]

**Comment by idealisms** [comment]
If it's helpful, here's stack trace:

java.lang.NullPointerException: null
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:63) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.helpers.FontHelper.renderFontLeftTopAligned(FontHelper.java:1257) ~[?:?]
	at InfoMod2.ui.widgets.tooltips.gold.ShopPriceToolTip.renderTitle(ShopPriceToolTip.java:129) ~[InfoMod2.jar:?]
	at InfoMod2.ui.widgets.tooltips.TitledToolTip.renderHeader(TitledToolTip.java:55) ~[InfoMod2.jar:?]
	at InfoMod2.ui.widgets.tooltips.TitledToolTip.renderForeground(TitledToolTip.java:66) ~[InfoMod2.jar:?]
	at InfoMod2.ui.widgets.tooltips.ExtendedToolTip.render(ExtendedToolTip.java:33) ~[InfoMod2.jar:?]
	at InfoMod2.ui.widgets.tooltips.groups.GoldTips.render(GoldTips.java:19) ~[InfoMod2.jar:?]
	at InfoMod2.patches.ToolTipPatches$TopBarExtendedToolTipRenderHelper.receivePostRender(ToolTipPatches.java:147) ~[InfoMod2.jar:?]
	at basemod.BaseMod.publishPostRender(BaseMod.java:2318) ~[?:?]
	at basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.RenderHooks$PostRenderHook.Insert(RenderHooks.java:70) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:482) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [?:?]

**Comment by casey-c** [comment]
Thanks for the stack trace @idealisms! I'll try to hunt this bug down once I get back from holiday as I'm away from my computer for the next few weeks. 

I'm also accepting merge requests if you're feeling adventurous and want to try and tackle it before then! :)

**Comment by casey-c** [comment]
Hopefully fixed with release 0.0.7
